// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package functional

// IfString是三目运算
// 例如，期望判断a,b的大小，a>=b的时候返回a，否则返回b
// 正常可写作
// ```
// if a >= b {
//     return a
// } else {
//     return b
// }
// ```
// 使用IfString，可简化为
// ```
// IfString(func() {return a >= b })(a)(b)
// ```
// 等价于JavaScript中`a>=b?a:b`
func IfString(condition func() bool) func(string) func(string) string {
	return func(trueValue string) func(string) string {
		return func(falseValue string) string {
			if condition() {
				return trueValue
			}
			return falseValue
		}
	}
}

// IfInt是三目运算
// 例如，期望判断a,b的大小，a>=b的时候返回a，否则返回b
// 正常可写作
// ```
// if a >= b {
//     return a
// } else {
//     return b
// }
// ```
// 使用IfInt，可简化为
// ```
// IfInt(func() {return a >= b })(a)(b)
// ```
// 等价于JavaScript中`a>=b?a:b`
func IfInt(condition func() bool) func(int) func(int) int {
	return func(trueValue int) func(int) int {
		return func(falseValue int) int {
			if condition() {
				return trueValue
			}
			return falseValue
		}
	}
}

// IfInt64是三目运算
// 例如，期望判断a,b的大小，a>=b的时候返回a，否则返回b
// 正常可写作
// ```
// if a >= b {
//     return a
// } else {
//     return b
// }
// ```
// 使用IfInt64，可简化为
// ```
// IfInt64(func() {return a >= b })(a)(b)
// ```
// 等价于JavaScript中`a>=b?a:b`
func IfInt64(condition func() bool) func(int64) func(int64) int64 {
	return func(trueValue int64) func(int64) int64 {
		return func(falseValue int64) int64 {
			if condition() {
				return trueValue
			}
			return falseValue
		}
	}
}

// IfInt32是三目运算
// 例如，期望判断a,b的大小，a>=b的时候返回a，否则返回b
// 正常可写作
// ```
// if a >= b {
//     return a
// } else {
//     return b
// }
// ```
// 使用IfInt32，可简化为
// ```
// IfInt32(func() {return a >= b })(a)(b)
// ```
// 等价于JavaScript中`a>=b?a:b`
func IfInt32(condition func() bool) func(int32) func(int32) int32 {
	return func(trueValue int32) func(int32) int32 {
		return func(falseValue int32) int32 {
			if condition() {
				return trueValue
			}
			return falseValue
		}
	}
}
