// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package compare

func MaxInt(arg int, others ...int) int {
	max := arg
	for _, other := range others {
		if other > max {
			max = other
		}
	}
	return max
}

func MaxInt64(arg int64, others ...int64) int64 {
	max := arg
	for _, other := range others {
		if other > max {
			max = other
		}
	}
	return max
}

func MaxInt32(arg int32, others ...int32) int32 {
	max := arg
	for _, other := range others {
		if other > max {
			max = other
		}
	}
	return max
}

func MaxFloat64(arg float64, others ...float64) float64 {
	max := arg
	for _, other := range others {
		if other > max {
			max = other
		}
	}
	return max
}

func MaxFloat32(arg float32, others ...float32) float32 {
	max := arg
	for _, other := range others {
		if other > max {
			max = other
		}
	}
	return max
}
